config/routes.rb
Rails.application.routes.draw do
  root 'brides#index' 
  get "/signin", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  get "/auth/facebook/callback", to: "sessions#create"
  get "/signout", to: "sessions#destroy"
  get "/dresses/longest", to: "dresses#longest"

  resources :brides, only: [:new, :create, :index, :show, :edit, :update] do
    # nested resource
    resources :bridesmaids, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

  resources :dresses, only: [:new, :create, :index, :show, :edit, :update] do
    resources :comments
  end
end

app/models/bride.rb
class Bride < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  has_secure_password
  has_many :bridesmaids
  has_many :dresses, through: :bridesmaids
end

app/models/bridesmaid.rb
class Bridesmaid < ActiveRecord::Base
  validates :name, presence: true
  validates :dress_id, presence: true
  belongs_to :bride
  belongs_to :dress
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :dress
end

app/models/dress.rb
class Dress < ActiveRecord::Base
  has_many :bridesmaids
  has_many :brides, through: :bridesmaids
  validates :link, presence: true
  validates :material, presence: true
  validates :length, presence: true
  validates_numericality_of :length, :on => :create
  accepts_nested_attributes_for :bridesmaids
  has_many :comments

  def self.longest_dress
    all.order(length: :desc).limit(1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
  before_action :current_user
  #before_action :authentication_required, except: [:new, :create, :index, :show]
  helper_method :current_user, :logged_in?
  layout "application"
  #before_action :authentication_required, except: [:index, :create, :new]

  def authentication_required
    if !logged_in?
      redirect_to_root
    end
  end

  def logged_in?
    !!current_user
  end

  def current_user
    #byebug
    @current_user ||= Bride.find(session[:bride_id]) if session[:bride_id]
  end

  private

  def redirect_to_root
    redirect_to root_path
  end

end

app/controllers/brides_controller.rb
class BridesController < ApplicationController

  before_action :redirect_to_root, :unless => :bride_self?, :only => [:edit, :update]

  def show
    @bride = Bride.find(params[:id])
    @bridesmaids = @bride.bridesmaids
    #byebug
  end
  
  def index
    @brides = Bride.all
  end

  def new
    @bride = Bride.new
  end

  def create
    @bride = Bride.new(bride_params)
    if @bride.save 
      session[:bride_id] = @bride.id
      redirect_to bride_path(@bride)
    else
      render :new
    end
  end

  def edit
    #byebug
    @bride = Bride.find(params[:id])
  end

  def update
    @bride = Bride.find(params[:id])
    if @bride.update(bride_params)
      redirect_to bride_path(@bride)
    else
      render :edit
    end
    
  end

private

    def bride_params
      params.require(:bride).permit(:name, :password, :grooms_name)
    end  

    def bride_self?
      #byebug
      current_user.id == params[:id].to_i
    end

end

app/controllers/bridesmaids_controller.rb
class BridesmaidsController < ApplicationController

    before_action :redirect_to_root, :unless => :bride_bridesmaid_self?, :except => [:index]

    def new
        @bride = Bride.find(params[:bride_id])
        @bridesmaid = @bride.bridesmaids.build
        @dresses = Dress.all
    end

    def create
        @bridesmaid = Bridesmaid.new(bridesmaid_params)
        @bridesmaid.dress = Dress.find(params[:bridesmaid][:dress_id])
        @bride = Bride.find(params[:bride_id ])
        if @bridesmaid.save
            redirect_to bride_bridesmaids_path(@bride)
        else 
            render :new
        end
    end

    def index
        @bride = Bride.find(params[:bride_id])
        @bridesmaids = @bride.bridesmaids
        #byebug
    end

    def edit
        @bride = Bride.find(params[:bride_id])
        @bridesmaid = Bridesmaid.find(params[:id])
        @dress = Dress.find(@bridesmaid.dress_id)
        @dresses = Dress.all
    end   

    def update
        @bridesmaid = Bridesmaid.find(params[:id])
        @bridesmaid.name = bridesmaid_params[:name]
        @bridesmaid.dress = Dress.find(params[:bridesmaid][:dress_id])
        @bride = Bride.find(params[:bride_id])
        if @bridesmaid.save
            redirect_to bride_bridesmaids_path(@bride)
        else 
            render :edit
        end
    end

    def show
        @bridesmaid = Bridesmaid.find(params[:id])
    end

    def destroy
        @bride = Bride.find(params[:bride_id])
        @bridesmaid = Bridesmaid.find(params[:id])
        @bridesmaid.destroy
        redirect_to bride_path(@bride)
    end

    
    private
    
        def bridesmaid_params
            params.require(:bridesmaid).permit(:name, :bride_id, :id)
        end

        def bride_bridesmaid_self?
            #byebug
            current_user.id == params[:bride_id].to_i
        end

end

app/controllers/comments_controller.rb
require 'byebug'

class CommentsController < ApplicationController
    
    def index
		@dress = Dress.find(params[:dress_id])
        @comments = @dress.comments.all
        render json: @comments
    end

    def new
        @dress = Dress.find(params[:dress_id])
        @comment = Comment.new
        @url = new_dress_comment_path(@dress)
        
        respond_to do |format|
            format.html {redirect_to @dress}
            format.js
        end

    end
    
    def create 
        @dress = Dress.find(params[:dress_id])
        @comment = @dress.comments.new(comment_params)
        if @comment.save
            respond_to do |format|
                format.html {redirect_to @dress}
                format.js
            end
		else 
			flash[:notice] = "This couldn't be saved"
			redirect_to new_dress_comment_path(@dress)
		end
	end

    def show
        #byebug
		@comment= Comment.find(params[:id])
	end
    
    def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
    end

private

    def comment_params
		params.require(:comment).permit(:dress_id, :comment)
	end


end

app/controllers/dresses_controller.rb
require 'byebug'

class DressesController < ApplicationController

    def index
        @dresses = Dress.all
    end

    def new
        @dress = Dress.new
    end

    def create
        @dress = Dress.new(dress_params)
        if @dress.save
            redirect_to dress_path(@dress)
          else
            render :new
          end
    end

    def edit 
        @dress = Dress.find(params[:id])
    end

    def show
        @dress = Dress.find(params[:id])
        @comments = @dress.comments.all
    end

    def update
        @dress = Dress.find(params[:id])
        if @dress.update(dress_params)
            redirect_to dress_path(@dress)
        else
            render :edit
        end
    end

    def longest
        @dress = Dress.longest_dress.first
    end

    private
    
        def dress_params
          params.require(:dress).permit(:link, :material, :length)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
      def destroy
        session[:bride_id] = nil
        redirect_to root_url
      end
    
      def new
        @bride = Bride.new
        @brides = Bride.all
      end
    
      def create
        if params[:code].present?
          @bride= Bride.find_or_create_by(uid: auth['uid']) do |b|
            b.name = auth['info']['name']
          end
          session[:bride_id] = @bride.id
          redirect_to bride_path(@bride)
        else
          @bride = Bride.find_by(name: params[:bride][:name])
            if @bride && @bride.authenticate(params[:bride][:password])
              session[:bride_id] = @bride.id
              redirect_to bride_path(@bride)
            else
              redirect_to signin_path
            end
          end
      end
     
      private
     
      def auth
        request.env['omniauth.auth']
      end
    
    end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/brides/_form.html.erb
<% if @bride.errors.any? %>
<div id="error_explanation">
  <h3>There were some errors:</h3>
  <ul>
    <% @bride.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@bride) do |f| %>
    Name:
    <%= f.text_field :name, placeholder: "Enter your name" %><br>
    Password:
    <%= f.text_field :password, placeholder: "Enter a password" %><br>
    Groom's Name:
    <%= f.text_field :grooms_name, placeholder: "Enter the groom's name" %><br>
    <%= f.submit %>
<% end %>

app/views/brides/edit.html.erb
Edit Bride:
<%= render 'form' %>

app/views/brides/index.html.erb
<% @brides.each do |bride| %>
    <div>
    <strong>Bride Name: <%= bride.name %> </strong>
    <br>
    <%= link_to 'See Bride', bride_path(bride) %>
    <br>
    Groom's Name: <%= bride.grooms_name %>
    <br>
    <% @bridesmaids = bride.bridesmaids %>
    <%= render partial: "bridesmaids/bridesmaid_dresses" %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<% end %>

app/views/brides/new.html.erb
Welcome! Please create a profile so you can start organizing dress options!
<%= render 'form' %>

app/views/brides/show.html.erb
<strong>Name:</strong> <%= @bride.name %>
<br>
Groom's Name: <%= @bride.grooms_name %>
<br>
<%= render partial: "bridesmaids/bridesmaid_dresses" %> </br>
<br>
<% if logged_in? && @bride.id == current_user.id %>
    <%= link_to 'New Bridesmaid', new_bride_bridesmaid_path(:bride_id => @bride.id) %>
    <br>
    <%= link_to 'Edit Bride Profile', edit_bride_path(@bride) %>
<% end %>

app/views/bridesmaids/_bridesmaid_dresses.html.erb
<div class="row">

<% @bridesmaids.each do |bridesmaid| %>
    <div class="column" style="float:left">
        <img src="<%=bridesmaid.dress.link%>" alt="bridesmaid dress" height="250" >
        <br>
        Name: <%= bridesmaid.name %><br>
        Dress Material: <%= bridesmaid.dress.material %><br>
        Length: <%= bridesmaid.dress.length %> inches<br>
        <% if logged_in? && bridesmaid.bride.id == current_user.id %>
            <%= link_to 'Edit Bridesmaid', edit_bride_bridesmaid_path(:bride_id => bridesmaid.bride.id, :id => bridesmaid.id) %> <br>
            <%= button_to "Delete Bridesmaid", bride_bridesmaid_path(:bride_id => bridesmaid.bride.id, :id => bridesmaid.id), :method  => :delete %> 
        <% end %>       
    <br>
    <br>
    </div>
<% end %>

</div>

app/views/bridesmaids/_form.html.erb
<% if @bridesmaid.errors.any? %>
<div id="error_explanation">
  <h3>There were some errors:</h3>
  <ul>
    <% @bridesmaid.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for ([@bridesmaid.bride, @bridesmaid]) do |f| %>
    Name:
    <%= f.text_field :name, placeholder: "Enter bridesmaids name" %><br>
    <%= f.hidden_field :bride_id, value: @bride.id %>
    <%= f.label :dress_id, 'Pick a Dress:' %>
    <br>
    <% @dresses.each do |dress| %>
        <%= f.radio_button :dress_id, dress.id %> <img src="<%=dress.link%>" alt="dress" height="250" >
        <br>
    <% end %>
    <br><br>
    <%= f.submit %>
<% end %>

app/views/bridesmaids/edit.html.erb
Edit Bridesmaid:
<%= render 'form' %>

app/views/bridesmaids/index.html.erb
<html>
<%= @bride.name %>
<br><br>
<%= render partial: "bridesmaid_dresses" %>
<%= link_to 'New Bridesmaid', new_bride_bridesmaid_path(:bride_id => @bride.id) %>
</html>

app/views/bridesmaids/new.html.erb
Create a bridesmaid!
<%= render 'form' %>

app/views/bridesmaids/show.html.erb
<%= @bridesmaid.name %>

app/views/comments/_comment.html.erb
<li>
    <p>
        <%= comment.comment %>
    </p>
</li>

app/views/comments/_form.html.erb
<%= form_for [@dress, @dress.comments.new] do |f| %>
    <fieldset>
        <ol>
            <li> 
                <%= f.text_area :comment, rows:2, cols: 60,
                placeholder: "Leave a comment..." %>
            </li>
            <li>
                <%= f.submit 'Post Comment', class: 'button' %>
            </li>
        </ol>
    </fieldset>
<% end %>

app/views/comments/create.js.erb
$('#comments').append("<%= j render @comment %>");
$('#comment_body').val()

app/views/comments/new.js.erb
$('#new-comment').append("<%= j render @form %>");

app/views/dresses/_dresses.html.erb
<body>

<img src="<%=@dress.link%>" alt="dress" height="250" >
<br>
Dress Material: <%= @dress.material %>
<br>
Dress Length: <%= @dress.length %> inches
<br>
<%= link_to 'Edit Dress', edit_dress_path(@dress) %>
<button type="button" id="loadButton">See Comments</button>

<section id="commentsSection">
    <div id="comments"></div>
    <% if @comments.empty? %>
	<p>There are no comments. Would you like to add a comment?</p>
    <% end %>
    <%= link_to 'Add Comment', new_dress_comment_path(@dress) %>
    <div id="newComment></div>
</section>
</body>

app/views/dresses/_form.html.erb
<% if @dress.errors.any? %>
<div id="error_explanation">
  <h3>There were some errors:</h3>
  <ul>
    <% @dress.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for(@dress) do |f| %>
    Link:
    <%= f.text_field :link, placeholder: "Enter dress link" %><br>
    Dress Material:
    <%= f.text_field :material, placeholder: "Enter the dress material" %><br>
    Dress Length in Inches:
    <%= f.text_field :length, placeholder: "Enter the dress length:" %><br>
    <%= f.submit %>
<% end %>

app/views/dresses/edit.html.erb
Edit Dress!
<%= render 'form' %>

app/views/dresses/index.html.erb
Dresses
<br>
<html>
<% @dresses.each do |dress| %>
    <br>
    <img src="<%=dress.link%>" alt="dress" height="250" >
    <br>
    Dress Material: <%= dress.material %>
    <br>
    Dress Length: <%= dress.length %> inches
    <br>
    <%= link_to 'Edit Dress', edit_dress_path(dress) %> <%= link_to 'See Dress', dress_path(dress) %> 
<% end %>
</html>

app/views/dresses/longest.html.erb
The longest dress is:
<%= render partial: "dresses" %>

app/views/dresses/new.html.erb
Add a Dress:
<%= render 'form' %>

app/views/dresses/show.html.erb
<%= render partial: "dresses" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Unique Bridesmaid Dress Creater</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
    <h1>Unique Bridesmaid Dress Creater</h1>

    <ul class="nav navbar-nav">
      <% if current_user %>
        <li><%= link_to "Hello, #{current_user.name}!", bride_path(current_user) %></li>
        <li><%= link_to 'Add a Dress', new_dress_path %></li>
        <li><%= link_to "Log Out", signout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'New Bride Profile', new_bride_path %></li>
        <li><%= link_to "Sign In", signin_path %></li>
        <li><%= link_to('Log in with Facebook!', '/auth/facebook') %></li>
      <% end %>
        <li><%= link_to 'View All Brides', brides_path %></li>
        <li><%= link_to 'View All Dresses', dresses_path %></li>
        <li><%= link_to 'View Longest Dress', dresses_longest_path %></li>
    </ul>
    
    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>
  </body>
</html>